export const ActionTypes = {

    SET_PRODUCTS: "SET_PRODUCTS",
    SEARCH_PRODUCTS: "SEARCH_PRODUCTS",
    SELECTED_PRODUCTS: "SELECTED_PRODUCTS",
    PRODUCTS_INFO: "PRODUCTS_INFO",
    REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS",
    LENGTH: "LENGTH",
    INCREMENT:"INCREMENT",
    DECREMENT:"DECREMENT"



}

